In [2]:
import torch
import numpy as np
from torchvision import transforms

options = {
    (0, 0, 0),
    (0, 0, 45),
    (0, 1, 0),
    (0, 1, 45),
    (1, 0, 0),
    (1, 0, 45),
    (1, 1, 0),
    (1, 1, 45)
}

tensor = np.arange(18).reshape(2, 3, 3)
answer = []

for idx, option in enumerate(options):
    transform = transforms.Compose([
        transforms.RandomHorizontalFlip(p=option[0]),
        transforms.RandomVerticalFlip(p=option[1]),
        transforms.RandomRotation(degrees=option[2])
    ])
    answer[idx] = transform(tensor)

TypeError: img should be PIL Image. Got <class 'numpy.ndarray'>

In [7]:
array = np.arange(18).reshape(1, 2, 3, 3)
print(array)

print(np.flip(array, axis=2))
print(np.flip(array, axis=3))

[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]]]
[[[[ 6  7  8]
   [ 3  4  5]
   [ 0  1  2]]

  [[15 16 17]
   [12 13 14]
   [ 9 10 11]]]]
[[[[ 2  1  0]
   [ 5  4  3]
   [ 8  7  6]]

  [[11 10  9]
   [14 13 12]
   [17 16 15]]]]


In [12]:
array = np.arange(18).reshape(1, 2, 3, 3)
array2 = np.rot90(array, 1, (2, 3))

aa = np.concatenate((array, array2))

In [13]:
aa.shape

(2, 2, 3, 3)

In [14]:
lst = [[1, 2], [3, 4]]
np.flip(lst, axis=1)

array([[2, 1],
       [4, 3]])

In [1]:
import numpy as np
import torch

In [3]:
array = torch.arange(18).view(1, 2, 3, 3)
print(array)

print(torch.flip(array, dims=[2]))
print(torch.flip(array, dims=[3]))
print(torch.flip(array, dims=[2, 3]))

tensor([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],

         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]]])
tensor([[[[ 6,  7,  8],
          [ 3,  4,  5],
          [ 0,  1,  2]],

         [[15, 16, 17],
          [12, 13, 14],
          [ 9, 10, 11]]]])
tensor([[[[ 2,  1,  0],
          [ 5,  4,  3],
          [ 8,  7,  6]],

         [[11, 10,  9],
          [14, 13, 12],
          [17, 16, 15]]]])
tensor([[[[ 8,  7,  6],
          [ 5,  4,  3],
          [ 2,  1,  0]],

         [[17, 16, 15],
          [14, 13, 12],
          [11, 10,  9]]]])


In [26]:
import random

def trans_board(state):
    if random.randint(0, 7) == 0:
        return state
    elif random.randint(0, 7) == 1:
        return torch.rot90(state, k=1, dims=[1, 2])
    elif random.randint(0, 7) == 2:
        return torch.flip(state, dims=[1])
    elif random.randint(0, 7) == 3:
        return torch.rot90(torch.flip(state, dims=[1]), k=1, dims=[1, 2])
    elif random.randint(0, 7) == 4:
        return torch.flip(state, dims=[2])
    elif random.randint(0, 7) == 5:
        return torch.rot90(torch.flip(state, dims=[2]), k=1, dims=[1, 2])
    elif random.randint(0, 7) == 6:
        return torch.flip(torch.flip(state, dims=[2]), dims=[1])
    elif random.randint(0, 7) == 7:
        return torch.rot90(torch.flip(torch.flip(state, dims=[2]), dims=[1]), k=1, dims=[1, 2])

print(trans_board(array[0]))

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])


In [27]:
if torch.randint(0, 8, (1,))[0] == 2:
    print('hello')

In [28]:
import random 

if random.randint(0, 8) < 10:
    print('ff')

ff
