In [1]:
import numpy as np

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
ranked_moves = np.random.choice(
            a, 20, replace=True
        )
ranked_moves

array([4, 4, 8, 8, 5, 0, 2, 7, 5, 5, 2, 4, 5, 3, 4, 6, 6, 7, 8, 5])

In [4]:
ranked_moves[0].dtype

dtype('int32')

In [7]:
def rank_moves_eps_greedy(values):
    if np.random.random() < 0 :
        values = np.random.random(values.shape)
    # This ranks the moves from worst to best.
    ranked_moves = np.argsort(values)
    # Return them in best-to-worst order.
    return ranked_moves[::-1]

lst = [0.2, 0.6, 0.5, 1.0, 0]
result = rank_moves_eps_greedy(lst)
result

array([3, 1, 2, 0, 4], dtype=int64)

In [10]:
row = ranked_moves[18] // 9
col = ranked_moves[18] % 9
row.dtype

dtype('int32')